# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 5.9.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from gridly.paths.v1_branches.get import CallList
from gridly.paths.v1_branches.post import Create
from gridly.paths.v1_branches_diffcheck.post import CreateDiffCheck
from gridly.paths.v1_branches_branch_id.delete import Delete
from gridly.paths.v1_branches_branch_id.get import Get
from gridly.paths.v1_branches_diffcheck_task_id.get import GetDiffCheck
from gridly.paths.v1_branches_branch_id_merge.post import Merge


class BranchApi(
    CallList,
    Create,
    CreateDiffCheck,
    Delete,
    Get,
    GetDiffCheck,
    Merge,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
