# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 5.9.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from gridly.paths.v1_cdns.get import CallList
from gridly.paths.v1_cdns_cdn_id_publish.put import Publish
from gridly.paths.v1_cdns_cdn_id_unpublish.put import UnPublish


class CdnApi(
    CallList,
    Publish,
    UnPublish,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
