# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.33.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from gridly.paths.v1_databases.get import CallList
from gridly.paths.v1_databases.post import Create
from gridly.paths.v1_databases_db_id.delete import Delete
from gridly.paths.v1_databases_db_id_duplicate.post import Duplicate
from gridly.paths.v1_databases_db_id.get import Get
from gridly.paths.v1_databases_db_id.put import Update


class DatabaseApi(
    CallList,
    Create,
    Delete,
    Duplicate,
    Get,
    Update,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
