# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 5.9.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from gridly.paths.v1_glossaries.post import Create
from gridly.paths.v1_glossaries_id.delete import Delete
from gridly.paths.v1_glossaries_id_export.get import ExportFile
from gridly.paths.v1_glossaries_id.get import Get
from gridly.paths.v1_glossaries.get import GetAll
from gridly.paths.v1_glossaries_id_import.post import ImportFile
from gridly.paths.v1_glossaries_id.put import Update


class GlossaryApi(
    Create,
    Delete,
    ExportFile,
    Get,
    GetAll,
    ImportFile,
    Update,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
