# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.33.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from gridly.paths.v1_views_view_id_shares.put import Create
from gridly.paths.v1_views_view_id_shares.delete import Delete
from gridly.paths.v1_views_view_id_shares.get import Get


class ShareViewApi(
    Create,
    Delete,
    Get,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
