# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.33.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from gridly.paths.v1_views_view_id_columns_column_id_add.post import Add
from gridly.paths.v1_views_view_id_columns_bulk.post import BulkCreate
from gridly.paths.v1_views_view_id_columns.post import Create
from gridly.paths.v1_views_view_id_columns_column_id.delete import Delete
from gridly.paths.v1_views_view_id_columns_column_id.get import Get
from gridly.paths.v1_views_view_id_columns_column_id_remove.post import Remove
from gridly.paths.v1_views_view_id_columns_column_id.patch import Update


class ViewColumnApi(
    Add,
    BulkCreate,
    Create,
    Delete,
    Get,
    Remove,
    Update,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
