# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 5.9.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from gridly.paths.v1_views.get import CallList
from gridly.paths.v1_views.post import Create
from gridly.paths.v1_views_view_id_export.get import Export
from gridly.paths.v1_views_view_id.get import Get
from gridly.paths.v1_views_view_id_statistic.get import GetStatistic
from gridly.paths.v1_views_view_id_import.post import ImportView
from gridly.paths.v1_views_view_id_merge.post import Merge


class ViewApi(
    CallList,
    Create,
    Export,
    Get,
    GetStatistic,
    ImportView,
    Merge,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
