"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.15.1
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import gridly
from gridly.api.grid_api import GridApi  # noqa: E501


class TestGridApi(unittest.TestCase):
    """GridApi unit test stubs"""

    def setUp(self):
        self.api = GridApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        create  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        delete  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        get  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        list  # noqa: E501
        """
        pass

    def test_list_template_grids(self):
        """Test case for list_template_grids

        listTemplateGrids  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
