"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.15.1
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import gridly
from gridly.api.view_column_api import ViewColumnApi  # noqa: E501


class TestViewColumnApi(unittest.TestCase):
    """ViewColumnApi unit test stubs"""

    def setUp(self):
        self.api = ViewColumnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add(self):
        """Test case for add

        add  # noqa: E501
        """
        pass

    def test_create(self):
        """Test case for create

        create  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        delete  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        get  # noqa: E501
        """
        pass

    def test_remove(self):
        """Test case for remove

        remove  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
