"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.15.1
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import gridly
from gridly.api.view_file_api import ViewFileApi  # noqa: E501


class TestViewFileApi(unittest.TestCase):
    """ViewFileApi unit test stubs"""

    def setUp(self):
        self.api = ViewFileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete(self):
        """Test case for delete

        delete  # noqa: E501
        """
        pass

    def test_download(self):
        """Test case for download

        download  # noqa: E501
        """
        pass

    def test_upload(self):
        """Test case for upload

        upload  # noqa: E501
        """
        pass

    def test_upload_zip(self):
        """Test case for upload_zip

        uploadZip  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
