"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.15.1
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import gridly
from gridly.api.view_dependency_api import ViewDependencyApi  # noqa: E501


class TestViewDependencyApi(unittest.TestCase):
    """ViewDependencyApi unit test stubs"""

    def setUp(self):
        self.api = ViewDependencyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        create  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        delete  # noqa: E501
        """
        pass

    def test_delete_by_id(self):
        """Test case for delete_by_id

        deleteById  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        get  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        list  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
