"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 4.29.1
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import gridly
from gridly.api.glossary_api import GlossaryApi  # noqa: E501


class TestGlossaryApi(unittest.TestCase):
    """GlossaryApi unit test stubs"""

    def setUp(self):
        self.api = GlossaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        Create a new glossary  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete a glossary  # noqa: E501
        """
        pass

    def test_export_file(self):
        """Test case for export_file

        Export a glossary  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        get glossary info  # noqa: E501
        """
        pass

    def test_get_all(self):
        """Test case for get_all

        List all glossaries  # noqa: E501
        """
        pass

    def test_import_file(self):
        """Test case for import_file

        Import a glossary from file  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update glossary info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
