# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 5.9.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gridly import schemas  # noqa: F401


class MovePath(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class names(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'names':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            fromParentPath = schemas.StrSchema
            toParentPath = schemas.StrSchema
            moveBefore = schemas.StrSchema
            moveAfter = schemas.StrSchema
            __annotations__ = {
                "names": names,
                "fromParentPath": fromParentPath,
                "toParentPath": toParentPath,
                "moveBefore": moveBefore,
                "moveAfter": moveAfter,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["names"]) -> MetaOapg.properties.names: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fromParentPath"]) -> MetaOapg.properties.fromParentPath: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["toParentPath"]) -> MetaOapg.properties.toParentPath: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["moveBefore"]) -> MetaOapg.properties.moveBefore: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["moveAfter"]) -> MetaOapg.properties.moveAfter: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["names", "fromParentPath", "toParentPath", "moveBefore", "moveAfter", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["names"]) -> typing.Union[MetaOapg.properties.names, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fromParentPath"]) -> typing.Union[MetaOapg.properties.fromParentPath, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["toParentPath"]) -> typing.Union[MetaOapg.properties.toParentPath, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["moveBefore"]) -> typing.Union[MetaOapg.properties.moveBefore, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["moveAfter"]) -> typing.Union[MetaOapg.properties.moveAfter, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["names", "fromParentPath", "toParentPath", "moveBefore", "moveAfter", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        names: typing.Union[MetaOapg.properties.names, list, tuple, schemas.Unset] = schemas.unset,
        fromParentPath: typing.Union[MetaOapg.properties.fromParentPath, str, schemas.Unset] = schemas.unset,
        toParentPath: typing.Union[MetaOapg.properties.toParentPath, str, schemas.Unset] = schemas.unset,
        moveBefore: typing.Union[MetaOapg.properties.moveBefore, str, schemas.Unset] = schemas.unset,
        moveAfter: typing.Union[MetaOapg.properties.moveAfter, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MovePath':
        return super().__new__(
            cls,
            *args,
            names=names,
            fromParentPath=fromParentPath,
            toParentPath=toParentPath,
            moveBefore=moveBefore,
            moveAfter=moveAfter,
            _configuration=_configuration,
            **kwargs,
        )
