# coding: utf-8

"""
    Gridly API

    Gridly API documentation  # noqa: E501

    The version of the OpenAPI document: 5.9.0
    Contact: support@gridly.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from gridly import schemas  # noqa: F401


class TranslationStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "upToDate": "UP_TO_DATE",
            "outOfDate": "OUT_OF_DATE",
            "unset": "UNSET",
        }
    
    @schemas.classproperty
    def UP_TO_DATE(cls):
        return cls("upToDate")
    
    @schemas.classproperty
    def OUT_OF_DATE(cls):
        return cls("outOfDate")
    
    @schemas.classproperty
    def UNSET(cls):
        return cls("unset")
